# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rohit at 1 A.U.
tagline:          ''
description:      "My experiences with Python, D3, and Data Analysis"
url:              http://rohitx.github.io/index.html
baseurl:          /

author:
  name:           'Rohit Deshpande'
  url:            https://twitter.com/singlebinary

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
